version: '3'

dotenv: ['.env']

tasks:
  build:cli:
    cmds:
      - go build -o ./bin/cli cmd/cli/main.go

  run:cli:
    cmds:
      - reflex -r '\.go' -s -- sh -c 'go run ./cmd/cli'

  new:migration:
    cmds:
      - goose -s -dir ./sql/migrations create {{.CLI_ARGS}} sql

  migrate:up:
    cmds:
      - goose -dir ./sql/migrations up
      -
  migrate:down:
    cmds:
      - goose -dir ./sql/migrations down