name: ci
on:
  push

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-task@v1
        with:
          version: 3.10.0
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.18'

      - name: Build the CLI
        run: task build:cli

      #- name: Install dependencies
      #  run: go install github.com/pressly/goose/v3/cmd/goose@latest

      #- name: Run unit tests
      #  run: task test